### ISSUE TITLE
winwing_fcu error

### ISSUE THREAD

**Issue by mmaechtel** [schenlap/winwing_fcu#6]
Hi,

great project! Using it all the time. Did an update to recent master:

commit a38f2bcde7431560169b7a10fa026256fd8fd9b8 (HEAD -> main, origin/main, origin/HEAD)

And get a:
________________________________
python3 winwing_fcu.py 
using /usr/lib/x86_64-linux-gnu/libusb-1.0.so.0
now searching for winwing FCU ... found
compatible with X-Plane 11/12 and all Toliss Airbus
Traceback (most recent call last):
  File "/home/maechtel/winwing_fcu/winwing_fcu.py", line 862, in <module>
    main() 
    ^^^^^^
  File "/home/maechtel/winwing_fcu/winwing_fcu.py", line 816, in main
    winwing_fcu_set_leds(fcu_out_endpoint, [Leds.SCREEN_BACKLIGHT, Leds.EFISR_SCREEN_BACKLIGHT], 180)
  File "/home/maechtel/winwing_fcu/winwing_fcu.py", line 229, in winwing_fcu_set_leds
    winwing_fcu_set_led(ep, leds[i], brightness)
  File "/home/maechtel/winwing_fcu/winwing_fcu.py", line 242, in winwing_fcu_set_led
    cmd = bytes(data)
                ^^^^
UnboundLocalError: cannot access local variable 'data' where it is not associated with a value

**Comment by mmaechtel** [comment]
I do not have the efis, I think the elsif for me let me alone without the data var :)

**Comment by mmaechtel** [comment]
44097cf5c5ac6385a269701e3273491823c4dc42

ist the last one which works for me with only a fcu ....

**Comment by schenlap** [comment]
is fixed now
